### ISSUE TITLE
Remove "Success" on upload notification

### ISSUE THREAD

**Issue by yamanq** [Piwigo/piwigo-flutter-app#123]
This notification is intrusive when uploading multiple photos. Additionally, it is not even accurate. When I tried uploading an mp4 to an instance that does not support that filetype, I received both the "Success" notification and a small banner at the bottom of the app that said "Upload Error". Instead, the success indicator should be similar to the Upload Error message.

Screenshot after uploading an mp4 to an instance that does not support it:
![screenshot](https://user-images.githubusercontent.com/8166212/170355927-46a826f2-30d9-4666-a560-01fa65d67230.png)

**Comment by remi-martin** [comment]
This should be fixed with v1.1.0

**Comment by yamanq** [comment]
While the incorrect notification was fixed, can the notification be removed completely on success? When I upload many photos in a row (each into a different album), I get multiple notifications that block the screen. I suggest that a small "Success" indicator appears at the bottom of the app like the "Upload Error" indicator in the image above.

**Comment by remi-martin** [comment]
Hi,
I think I should add a setting for this.
Concerning the multiple notifications, each time you upload a set of photos / videos, it calls a function that will send a notification at the end of the process. It would be better to have a single process with a waiting list so that every new upload will add its photos to this list, and only one notification will be sent when the list gets emptied.

**Comment by remi-martin** [comment]
- [x] Added a setting to enable / disable upload notification
- [x] Added a snackbar when upload is successful

**Comment by remi-martin** [comment]
Piwigo NG 1.2.0 is out on Github and may close this issue
