### ISSUE TITLE
Download functionality is broken

### ISSUE THREAD

**Issue by truckerboy** [Piwigo/piwigo-flutter-app#129]
When I am trying to download a photo from any album, it is showing a notification that file has been downloaded successfully. There are three issues:
1. Download location is not configurable in settings.
2. I cannot find the downloaded file anywhere on my phone. What is piwigo NG's hardcoded download location?
3. Tapping on the notification for successful download does nothing. Sane behavior would dictate opening the downloaded file with the default photo application on the phone.

**Comment by remi-martin** [comment]
Right now, download location is in default "Pictures" folder of the device. However it is possible that this directory isn't found and so the files are not downloaded.

Directory path: /storage/emulated/0/Pictures

The best way will still be to ask for a destination directory

**Comment by truckerboy** [comment]
Agreed. Thank you.

**Comment by remi-martin** [comment]
Yes and no, I'm reworking the download feature right now so I'll see what I can do. One problem is that the user can download multiple files at a time, so in this case it will open the directory instead of the picture (and video)

**Comment by remi-martin** [comment]
https://user-images.githubusercontent.com/71256855/193591580-2d53ca41-c0d7-479c-8fb9-b5adb530848b.mp4

Here is a quick video of the new download !
(added share feature btw)

**Comment by truckerboy** [comment]
This looks great. However will the app require me to choose the download location every time I hit the download button or just the first time? Additionally is this something configurable from the app settings?

I will need to test the functionality around opening of the picture in my picture app from the notification banner after downloading.

**Comment by remi-martin** [comment]
- [ ] Add a setting to choose the default download destination
- [ ] Add a setting to enable / disable notification
- [ ] When downloading, if default download destination is unset, ask if the user wants to set the chosen destination as default

**Comment by remi-martin** [comment]
Piwigo NG 1.2.0 is out on Github and may close this issue

**Comment by truckerboy** [comment]
> 

none of the two issues (129 or 130) seem fixed in 1.2.0. I downloaded the latest apk and even deleted storage and cache just to be sure. nothings changed from the google play version.

**Comment by remi-martin** [comment]
Yes this will be done later, I wanted to put a release this week because it has enough changes

**Comment by truckerboy** [comment]
Sounds good and thank you

**Comment by Catfriend1** [comment]
Piwigo ng 1.2.1 : when I long click on any picture in the overview, nothing happens. I expected the download/share menu to pop up. Am i doing something wrong?

**Comment by remi-martin** [comment]
Hi, I forgot to mention it in this issue but the package I used to open files after download has some unsafe permissions for the Play Store, so I had to remove it along with the feature. There are some alternatives, but they are not supported by the version of Flutter I am using for this project. Upgrading Flutter version is not that simple in this case because Piwigo NG was built without "null safety" which changes the syntax of the language. This is one of the reason why I am developing a v2.0.0.

This feature will come back when I'll be done with all this. I plan to release the 2.0 for December 2022 / January 2023.

**Comment by remi-martin** [comment]
Hi, I forgot to mention it in this issue but the package I used to open files after download has some unsafe permissions for the Play Store, so I had to remove it along with the feature. There are some alternatives, but they are not supported by the version of Flutter I am using for this project. Upgrading Flutter version is not that simple in this case because Piwigo NG was built without "null safety" which changes the syntax of the language. This is one of the reason why I am developing a v2.0.0.

This feature will come back when I'll be done with all this. I plan to release the 2.0 for December 2022 / January 2023.
